databases:
  - name: rankensteindb
    plan: free
    databaseName: rankenstein
    user: rankenstein

services:
  - type: web
    plan: free
    name: rankenstein
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn rankenstein.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rankensteindb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4